# Sales Performance and Regional Target Analysis
A company wants to analyze monthly sales performance across different sales representatives and regions.
You are given three datasets:
1. sales_reps: sales representative information
2. monthly_sales: monthly sales records
3. regions: regional sales targets

Using these datasets, do the following:
- Inspect the datasets and identify their columns and dimensions.
- Identify the common key columns and merge the tables.
- Create a new column for total_sales by multiplying units sold by unit price.
- Compare each sales representative’s total sales with the regional target.
- Create a new column showing whether the target was met or not met.
- Calculate the total sales by region.
- Calculate the average total sales by sales representative.
- Create a pivot table showing total sales by month and region.
- Check for missing values, duplicated keys, and unmatched rows.
- Reshape the data if needed to improve the monthly comparison.

In [7]:
import pandas as pd 

# Load the datasets
sales_reps = pd.read_excel("sales_reps.xlsx")

monthly_sales = pd.read_excel("monthly_sales.xlsx")

regions = pd.read_excel("regions.xlsx")

print("\nSales Representatives")
display(sales_reps)

print("\nMonthly Sales")
display(monthly_sales)

print("\nRegions")
display(regions)

# Identify their columns and dimensions
print("\nSales Representatives:", sales_reps.columns.tolist())
print("\nMonthly Sales:", monthly_sales.columns.tolist())
print("\nRegions:", regions.columns.tolist()) 

print("\nSales Representatives Shape", sales_reps.shape)
print("\nMonthly Sales Shape:", monthly_sales.shape)
print("\nRegions Shape:", regions.shape)


# Explain the common key used for merging
print("\nCommon key for merging (sales_reps vs montlhy_sales):", "rep_id")
print("\nCommon key for merging (sales_reps vs regions):", "region_id")

Sales Representatives

   rep_id rep_name region_id
0     301   Daniel       R01
1     302    Chloe       R02
2     303    Lucas       R01
3     304      Mia       R03
4     305    James       R02
5     306     Ella       R04

Monthly Sales

   sale_id  rep_id month  units_sold  unit_price
0     7001     301   Jan          10         200
1     7002     302   Jan           8         180
2     7003     303   Jan          15         210
3     7004     304   Jan           6         190
4     7005     305   Jan           9         175
5     7006     306   Jan           7         220
6     7007     301   Feb          12         200
7     7008     302   Feb          11         180
8     7009     307   Feb          10         205

Regions

  region_id region_name  monthly_target
0       R01       North            4000
1       R02       South            3000
2       R03        East            2500
3       R04        West            3500
4       R05     Central            2800

Sales Representatives: ['rep_id', 'rep_name', 'region_id']

Monthly Sales: ['sale_id', 'rep_id', 'month', 'units_sold', 'unit_price']

Regions: ['region_id', 'region_name', 'monthly_target']

Sales Representatives Shape (6, 3)

Monthly Sales Shape: (9, 5)

Regions Shape: (5, 3)

Common key for merging (sales_reps vs montlhy_sales): rep_id

Common key for merging (sales_reps vs regions): region_id

In [8]:
import numpy as np

# Merge the sales_reps and monthly_sales tables
initial_sales_data = pd.merge(sales_reps, monthly_sales, on="rep_id", how="left")
sales_data = pd.merge(initial_sales_data, regions, on="region_id", how="left")

print("\nMerged Sales Data:")
display(sales_data)



# Create new column for total_sales
sales_data["total_sales"] = sales_data["units_sold"] * sales_data["unit_price"]

print("\nNew Total Sales Column")
display(sales_data[["rep_name", "month", "units_sold", "unit_price", "total_sales"]])



# Compare each sales reps total sales with regional target 
sales_data["target_met"] = np.where(sales_data["total_sales"] >= sales_data["monthly_target"], "Met", "Not Met")


print("\nSales Target Comparison Column")
display(sales_data[["rep_name", "total_sales", "region_name", "monthly_target", "target_met"]])

Merged Sales Data:

,rep_id,rep_name,region_id,sale_id,month,units_sold,unit_price,region_name,monthly_target
0,301,Daniel,R01,7001,Jan,10,200,North,4000
1,301,Daniel,R01,7007,Feb,12,200,North,4000
2,302,Chloe,R02,7002,Jan,8,180,South,3000
3,302,Chloe,R02,7008,Feb,11,180,South,3000
4,303,Lucas,R01,7003,Jan,15,210,North,4000
5,304,Mia,R03,7004,Jan,6,190,East,2500
6,305,James,R02,7005,Jan,9,175,South,3000
7,306,Ella,R04,7006,Jan,7,220,West,3500

New Total Sales Column

  rep_name month  units_sold  unit_price  total_sales
0   Daniel   Jan          10         200         2000
1   Daniel   Feb          12         200         2400
2    Chloe   Jan           8         180         1440
3    Chloe   Feb          11         180         1980
4    Lucas   Jan          15         210         3150
5      Mia   Jan           6         190         1140
6    James   Jan           9         175         1575
7     Ella   Jan           7         220         1540

Sales Target Comparison Column

  rep_name  total_sales region_name  monthly_target target_met
0   Daniel         2000       North            4000    Not Met
1   Daniel         2400       North            4000    Not Met
2    Chloe         1440       South            3000    Not Met
3    Chloe         1980       South            3000    Not Met
4    Lucas         3150       North            4000    Not Met
5      Mia         1140        East            2500    Not Met
6    James         1575       South            3000    Not Met
7     Ella         1540        West            3500    Not Met

In [9]:
# Calculate total sales by region 
sales_per_region = sales_data.groupby("region_name")["total_sales"].sum().sort_values(ascending=False)

print("\nTotal Sales per Region")
display(sales_per_region)


# Calculate average total sales by sales reps 
avg_sales_per_salesreps = sales_data.groupby("rep_name")["total_sales"].mean().sort_values(ascending=False)

print("\nAverage Total Sales per Sales Representatives")
display(avg_sales_per_salesreps)


# Create a pivot table that shows total sales by month and region 
pivot_table = pd.pivot_table(
    sales_data, 
    index="month",
    values="total_sales", 
    columns="region_name", 
    aggfunc="sum", 
    fill_value=0
)

print("\nPivot Table:")
display(pivot_table)

Total Sales per Region

region_name
North    7550
South    4995
West     1540
East     1140
Name: total_sales, dtype: int64

Average Total Sales per Sales Representatives

rep_name
Lucas     3150.0
Daniel    2200.0
Chloe     1710.0
James     1575.0
Ella      1540.0
Mia       1140.0
Name: total_sales, dtype: float64

Pivot Table:

region_name  East  North  South  West
month
Feb             0   2400   1980     0
Jan          1140   5150   3015  1540

In [10]:
# Check for missing values, duplicated keys, and unmatched rows. 

# First create a temporary merged tables using an outer join and add an indicator column 
first_sales_data = pd.merge(sales_reps, monthly_sales, on="rep_id", how="outer", indicator="merge_reps_sales")
temp_sales_data = pd.merge(first_sales_data, regions, on="region_id", how="outer", indicator="merge_with_regions")

print("\nTemporary Merged Sales Data:")
display(temp_sales_data) 

print("\nUnmatched Rows:")

print("\nRows Only in sales_reps:") 
display(temp_sales_data[temp_sales_data["merge_reps_sales"] == "left_only"]) 

print("\nRows Only in monthly_sales:") 
display(temp_sales_data[temp_sales_data["merge_reps_sales"] == "right_only"]) 

print("\nRows Only in final merge (regions):")
display(temp_sales_data[temp_sales_data["merge_with_regions"] != "both"])



# Check for missing values
missing_values = temp_sales_data.isna().sum()

print("\nMissing Values per column")
display(missing_values)


# Check for duplicated keys 
duplicated_keys = temp_sales_data.duplicated()

print("\nDuplicated Keys")
display(duplicated_keys)

Temporary Merged Sales Data:

,rep_id,rep_name,region_id,sale_id,month,units_sold,unit_price,merge_reps_sales,region_name,monthly_target,merge_with_regions
0,301.0,Daniel,R01,7001.0,Jan,10.0,200.0,both,North,4000.0,both
1,301.0,Daniel,R01,7007.0,Feb,12.0,200.0,both,North,4000.0,both
2,303.0,Lucas,R01,7003.0,Jan,15.0,210.0,both,North,4000.0,both
3,302.0,Chloe,R02,7002.0,Jan,8.0,180.0,both,South,3000.0,both
4,302.0,Chloe,R02,7008.0,Feb,11.0,180.0,both,South,3000.0,both
5,305.0,James,R02,7005.0,Jan,9.0,175.0,both,South,3000.0,both
6,304.0,Mia,R03,7004.0,Jan,6.0,190.0,both,East,2500.0,both
7,306.0,Ella,R04,7006.0,Jan,7.0,220.0,both,West,3500.0,both
8,NaN,NaN,R05,NaN,NaN,NaN,NaN,NaN,Central,2800.0,right_only
9,307.0,NaN,NaN,7009.0,Feb,10.0,205.0,right_only,NaN,NaN,left_only

Unmatched Rows:

Rows Only in sales_reps:

Empty DataFrame
Columns: [rep_id, rep_name, region_id, sale_id, month, units_sold, unit_price, merge_reps_sales, region_name, monthly_target, merge_with_regions]
Index: []

Rows Only in monthly_sales:

,rep_id,rep_name,region_id,sale_id,month,units_sold,unit_price,merge_reps_sales,region_name,monthly_target,merge_with_regions
9,307.0,NaN,NaN,7009.0,Feb,10.0,205.0,right_only,NaN,NaN,left_only

Rows Only in final merge (regions):

,rep_id,rep_name,region_id,sale_id,month,units_sold,unit_price,merge_reps_sales,region_name,monthly_target,merge_with_regions
8,NaN,NaN,R05,NaN,NaN,NaN,NaN,NaN,Central,2800.0,right_only
9,307.0,NaN,NaN,7009.0,Feb,10.0,205.0,right_only,NaN,NaN,left_only

Missing Values per column

rep_id                1
rep_name              2
region_id             1
sale_id               1
month                 1
units_sold            1
unit_price            1
merge_reps_sales      1
region_name           1
monthly_target        1
merge_with_regions    0
dtype: int64

Duplicated Keys

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [11]:
print("\nCurrent Sales Data")
display(sales_data)

# Reshape the main sales data to improe monthly comparison  

# Define month order 
month_order = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

# Convert month to ordered categorical
sales_data['new_month'] = pd.Categorical(sales_data['month'], categories=month_order, ordered=True)

# Create pivot table: months as rows, regions as columns, total sales as values
new_pivot_table = pd.pivot_table(
    sales_data,
    index='new_month',
    columns='region_name',
    values='total_sales',
    aggfunc='sum',
    observed=False
)

print("\nPivot Table for Monthly Comparison:")
display(new_pivot_table)

Current Sales Data

,rep_id,rep_name,region_id,sale_id,month,units_sold,unit_price,region_name,monthly_target,total_sales,target_met
0,301,Daniel,R01,7001,Jan,10,200,North,4000,2000,Not Met
1,301,Daniel,R01,7007,Feb,12,200,North,4000,2400,Not Met
2,302,Chloe,R02,7002,Jan,8,180,South,3000,1440,Not Met
3,302,Chloe,R02,7008,Feb,11,180,South,3000,1980,Not Met
4,303,Lucas,R01,7003,Jan,15,210,North,4000,3150,Not Met
5,304,Mia,R03,7004,Jan,6,190,East,2500,1140,Not Met
6,305,James,R02,7005,Jan,9,175,South,3000,1575,Not Met
7,306,Ella,R04,7006,Jan,7,220,West,3500,1540,Not Met

Pivot Table for Monthly Comparison:

region_name  East  North  South  West
new_month
Jan          1140   5150   3015  1540
Feb             0   2400   1980     0
Mar             0      0      0     0
Apr             0      0      0     0
May             0      0      0     0
Jun             0      0      0     0
Jul             0      0      0     0
Aug             0      0      0     0
Sep             0      0      0     0
Oct             0      0      0     0
Nov             0      0      0     0
Dec             0      0      0     0